### ISSUE TITLE
User account images are saved in the wrong folder

### ISSUE THREAD

**Issue by philipmarnef** [steirico/kirby-plugin-image-crop-field#6]
The cropped image filepath is lowercased in `fields/CroppedImage.php`, but user accounts folders are case-sensitive. As a result they end up in a new folder.

What is the reason for lowercasing the path?

**Comment by steirico** [comment]
Well, I investigated the way how directory names in `content` and `media` are generated from a page's title. I concluded that `str::slug()` is involved which leads to lower case paths. That was the reason for the lower case in the mentioned code.

I see your point and I can confirm that `user` folders in `media` are mixed case.

So this issue indeed arises when using the plugin in user blueprints.

**Comment by steirico** [comment]
@philipmarnef: Give a try to branch `bug/lower-case-paths`.

It should fix this issue.

**Comment by philipmarnef** [comment]
Just checked out the branch and can confirm it resolves the issue. Thanks.

**Comment by steirico** [comment]
Good hear. Thanks for testing!

**Comment by steirico** [comment]
Fixed in c933c8403b7a20579474234b819499e587ebd5e5
